// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnarnB28gAwx8qK2FqJEV0yMXmMyGsQgM',
    appId: '1:102336053435:web:a2ec370d6cbc008694299e',
    messagingSenderId: '102336053435',
    projectId: 'test-65e03',
    authDomain: 'test-65e03.firebaseapp.com',
    databaseURL: 'https://test-65e03.firebaseio.com',
    storageBucket: 'test-65e03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDNtiCKVCOTgHpcPKkxlYoKFLKjnlMeg',
    appId: '1:102336053435:android:356b1bb66442ea1e94299e',
    messagingSenderId: '102336053435',
    projectId: 'test-65e03',
    databaseURL: 'https://test-65e03.firebaseio.com',
    storageBucket: 'test-65e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcE-J49FdUrLeQrWHq_-CCWnSZWLsz3cg',
    appId: '1:102336053435:ios:5fb8accbdc91574494299e',
    messagingSenderId: '102336053435',
    projectId: 'test-65e03',
    databaseURL: 'https://test-65e03.firebaseio.com',
    storageBucket: 'test-65e03.firebasestorage.app',
    iosBundleId: 'com.shopy.shopyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcE-J49FdUrLeQrWHq_-CCWnSZWLsz3cg',
    appId: '1:102336053435:ios:5fb8accbdc91574494299e',
    messagingSenderId: '102336053435',
    projectId: 'test-65e03',
    databaseURL: 'https://test-65e03.firebaseio.com',
    storageBucket: 'test-65e03.firebasestorage.app',
    iosBundleId: 'com.shopy.shopyMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnarnB28gAwx8qK2FqJEV0yMXmMyGsQgM',
    appId: '1:102336053435:web:1daa3a4c955971cb94299e',
    messagingSenderId: '102336053435',
    projectId: 'test-65e03',
    authDomain: 'test-65e03.firebaseapp.com',
    databaseURL: 'https://test-65e03.firebaseio.com',
    storageBucket: 'test-65e03.firebasestorage.app',
  );
}
